# Generated by Django 4.0.6 on 2022-07-07 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='birth',
            name='photo',
            field=models.ImageField(upload_to='media/birth'),
        ),
        migrations.AlterField(
            model_name='marriage',
            name='husband_photo',
            field=models.ImageField(upload_to='media/marriage'),
        ),
        migrations.AlterField(
            model_name='marriage',
            name='wife_photo',
            field=models.ImageField(upload_to='media/marriage'),
        ),
    ]
