# Generated by Django 4.0.6 on 2022-07-07 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0003_alter_birth_photo_alter_marriage_husband_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='death',
            name='death_reason',
            field=models.TextField(default='some reason'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='divorce',
            name='divorce_reason',
            field=models.TextField(default='some reason'),
            preserve_default=False,
        ),
    ]
