# Generated by Django 4.0.6 on 2022-07-08 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0006_alter_birth_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='birth',
            name='photo',
            field=models.ImageField(upload_to='birth'),
        ),
    ]
