# Generated by Django 4.0.6 on 2022-07-08 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0007_alter_birth_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='death',
            name='photo',
            field=models.ImageField(default='default.png', upload_to='death'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='divorce',
            name='husband_photo',
            field=models.ImageField(default='default.png', upload_to='marriage'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='divorce',
            name='wife_photo',
            field=models.ImageField(default='default.png', upload_to='marriage'),
            preserve_default=False,
        ),
    ]
